- name: install keyczar
  hosts: www
  sudo: true

  tasks:
  - yum: state=installed name=python-keyczar

- name: Set up WWW server
  accelerate: true
  hosts: www
  sudo: true

  vars_files:
  - vars/common.yml
  - private/passwords.yml

  roles:
  - common
  - nginx
  - pgsql
  - python
  - ruby
  - discourse #requires common, nginx, pgsql
  - spiff  # requires common, nginx, pgsql
  - gollum # requires common, nginx

